/* ICA 5 Ch7 questions 9-26 */
/*
SELECT *
FROM CUSTOMER
;
SELECT *
FROM INVOICE
;
SELECT *
FROM VENDOR
;
SELECT *
FROM PRODUCT
;
SELECT
FROM LINE
;

-- 9
SELECT COUNT(INV_NUMBER) AS NumInvoices
FROM INVOICE
;

-- 10 
SELECT COUNT(CUSTOMER.CUS_CODE) AS NumCust
FROM CUSTOMER
WHERE (CUSTOMER.CUS_BALANCE)>500
; 

-- 11 
SELECT INVOICE.CUS_CODE, INVOICE.INV_NUMBER, INVOICE.INV_DATE, PRODUCT.P_DESCRIPT, LINE_UNITS, LINE_PRICE
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER INNER JOIN PRODUCT ON LINE.P_CODE=PRODUCT.P_CODE
ORDER BY CUS_CODE, INV_NUMBER, P_DESCRIPT
;

-- 12 
SELECT INVOICE.CUS_CODE, INVOICE.INV_NUMBER, PRODUCT.P_DESCRIPT, LINE_UNITS, LINE_PRICE, (LINE_UNITS*LINE_PRICE) AS Subtotal
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER INNER JOIN PRODUCT ON LINE.P_CODE=PRODUCT.P_CODE
ORDER BY CUS_CODE, INV_NUMBER, P_DESCRIPT
;

-- 13
SELECT CUSTOMER.CUS_CODE,CUSTOMER.CUS_BALANCE, SUM((LINE_UNITS*LINE_PRICE)) AS TotalPurchases
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE=INVOICE.CUS_CODE INNER JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY CUS_CODE
;

-- 14
SELECT CUSTOMER.CUS_CODE,CUSTOMER.CUS_BALANCE, SUM((LINE_UNITS*LINE_PRICE)) AS TotalPurchases, COUNT(INVOICE.CUS_CODE) AS NumPurchases
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE=INVOICE.CUS_CODE INNER JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY CUS_CODE
;

-- 15
SELECT CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE, SUM((LINE_UNITS*LINE_PRICE)) AS TotalPurchases, COUNT(INVOICE.CUS_CODE) AS NumPurchases, (SUM((LINE_UNITS*LINE_PRICE))/COUNT(INVOICE.CUS_CODE)) AS AvgPurchAmount
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE=INVOICE.CUS_CODE INNER JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY CUS_CODE
;

-- 16
SELECT INVOICE.INV_NUMBER, SUM((LINE_UNITS*LINE_PRICE))AS InvoiceTotal
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY INV_NUMBER
;

-- 17
SELECT INVOICE.CUS_CODE, INVOICE.INV_NUMBER, SUM((LINE_UNITS*LINE_PRICE))AS InvoiceTotal
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY CUS_CODE, INV_NUMBER 
;

-- 18
SELECT CUS_CODE, COUNT(DISTINCT INVOICE.INV_NUMBER) AS NumOfInvoices, SUM(LINE_UNITS*LINE_PRICE) AS TotalPurchases
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY CUS_CODE
ORDER BY CUS_CODE
;

-- 19
SELECT SUM(NUMINVOICES) AS "Total Invoices", SUM(TOTPURCH) AS "Total Sales", MIN(TOTPURCH) AS "Minimum Customer Purchases", 
MAX(TOTPURCH) AS "Largest Customer Purchases", AVG(TOTPURCH) AS "Average Customer Purchases"
FROM (SELECT CUS_CODE, COUNT(DISTINCT INVOICE.INV_NUMBER) AS NUMINVOICES, SUM(LINE_UNITS * LINE_PRICE) AS TOTPURCH
      FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
      GROUP BY CUS_CODE) as emptotals
;

-- 20 
SELECT DISTINCT CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
ORDER BY CUS_CODE;

-- 21
SELECT MIN(CUS_BALANCE) AS "Minimum Balance", MAX(CUS_BALANCE) AS "Maximum Balance", AVG(CUS_BALANCE) AS "Average Balance"
FROM CUSTOMER JOIN INVOICE ON CUSTOMER.CUS_CODE=INVOICE.CUS_CODE
;

-- 22
SELECT SUM(CUS_BALANCE) AS "Total Balances", MIN(CUS_BALANCE) AS "Minimum Balance", MAX(CUS_BALANCE) AS "Maximum Balance", AVG(CUS_BALANCE) AS "Average Balance"
FROM CUSTOMER
;

-- 23
SELECT CUS_CODE, CUS_BALANCE
FROM CUSTOMER
WHERE CUSTOMER.CUS_CODE NOT IN (SELECT CUS_CODE FROM INVOICE)
ORDER BY CUS_CODE
;

-- 24
SELECT SUM(CUS_BALANCE) AS "Total Balances", MIN(CUS_BALANCE) AS "Minimum Balance", MAX(CUS_BALANCE) AS "Maximum Balance", AVG(CUS_BALANCE) AS "Average Balance"
FROM CUSTOMER
WHERE CUSTOMER.CUS_CODE NOT IN (SELECT CUS_CODE FROM INVOICE)
;
*/
-- 25
SELECT P_DESCRIPT, P_QOH, P_PRICE, (P_QOH*P_PRICE) AS SUBTOTAL 
FROM PRODUCT
ORDER BY  SUBTOTAL DESC
;

-- 26 
SELECT SUM(P_QOH*P_PRICE) AS "Total Value of Inventory"
FROM PRODUCT
;