/* ICA 4 ConstructCo */

/*
SELECT *
FROM ASSIGNMENT
; 
SELECT *
FROM EMPLOYEE
; 
SELECT *
FROM JOB
; 
SELECT *
FROM PROJECT
; 

SELECT EMPLOYEE.EMP_NUM, EMPLOYEE.EMP_LNAME, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_INITIAL
FROM EMPLOYEE
WHERE EMPLOYEE.EMP_LNAME LIKE'Smith%'
ORDER BY EMPLOYEE.EMP_NUM ASC
;
*/ 
SELECT PROJECT.PROJ_NAME, PROJECT.PROJ_VALUE, PROJECT.PROJ_BALANCE, EMPLOYEE.EMP_NUM, EMPLOYEE.EMP_LNAME, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_INITIAL, JOB.JOB_CODE, JOB.JOB_DESCRIPTION, JOB.JOB_CHG_HOUR
FROM EMPLOYEE JOIN PROJECT on EMPLOYEE.EMP_NUM = PROJECT.EMP_NUM INNER JOIN JOB on EMPLOYEE.JOB_CODE = JOB.JOB_CODE
-- ORDER BY PROJ_VALUE
ORDER BY EMP_LNAME
;
/*
SELECT DISTINCT PROJ_NUM 
FROM ASSIGNMENT
ORDER BY PROJ_NUM
; 

SELECT ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE, ASSIGN_HOURS, ASSIGN_CHG_HR
FROM ASSIGNMENT
ORDER BY ASSIGN_NUM
;
*/
SELECT EMPLOYEE.EMP_NUM, EMPLOYEE.EMP_LNAME, SUM(ASSIGN_HOURS) AS SumofASSIGN_HOURS, SUM(ASSIGN_CHARGE) AS SumofASSIGN_CHARGE
FROM ASSIGNMENT JOIN EMPLOYEE ON ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM
GROUP BY EMP_NUM
; 

SELECT PROJ_NUM, SUM(ASSIGN_HOURS) AS SumofASSIGN_HOURS, SUM(ASSIGN_CHARGE) AS SumofASSIGN_CHARGE
FROM ASSIGNMENT
GROUP BY PROJ_NUM
;

SELECT SUM(ASSIGN_HOURS) AS SumofSumASSIGN_HOURS, SUM(ASSIGN_CHARGE) AS SumofSumASSIGN_CHARGE
FROM ASSIGNMENT JOIN EMPLOYEE ON ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM
; 